config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]

  root '/', action: :welcome, controller: :sessions

  get 'login', action: :new, controller: :sessions
  post 'login', action: :create, controller: :sessions

  get 'logout', action: :destroy, controller: :sessions

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def create
    @user = User.find_by(username: params[:username])

    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navbar.html.erb
<div data-controller="theme">
  <span class="absolute text-white text-4xl top-5 left-4 cursor-pointer" onclick="open_nav()">
    <i class="bi bi-filter-left px-2 dark:bg-gray-900 bg-gray-100 dark:text-gray-100 text-gray-900 rounded-md"></i>
  </span>
  <div class="sidebar fixed top-0 bottom-0 lg:left-0 left-[-250px] p-2 w-[250px] overflow-y-auto text-center dark:bg-gray-900 bg-gray-200 shadow h-screen">
    <div class="font-bold dark:text-gray-100 text-gray-900 text-xl">
      <div class="p-2.5 mt-1 flex items-center rounded-md">
        <%#<%= image_tag("logo.png", alt: "Planit", width: 150, class: "mx-auto") %>
        <%= link_to image_tag("logo.png", alt: "Planit", width: 150), root_path, class: "mx-auto" %>
        <i class="bi bi-x cursor-pointer lg:hidden" onclick="open_nv()"></i>
      </div>

      <div>
        <% if logged_in? %>
          <%= link_to root_path, method: :get do %>
            <div class="p-2.5 mt-2 flex items-center rounded-md px-4 duration-300 cursor-pointer dark:hover:bg-gray-700 hover:bg-gray-400">
              <i class="bi bi-house-door-fill"></i>
              <span class="text-[15px] ml-4 dark:text-gray-200 text-gray-900">Home</span>
            </div>
          <% end %>
          <div class="p-2.5 mt-2 flex items-center rounded-md px-4 duration-300 cursor-pointer dark:hover:bg-gray-700 hover:bg-gray-400">
            <i class="bi bi-list-check"></i>
            <span class="text-[15px] ml-4 dark:text-gray-200 text-gray-900">To-Do</span>
          </div>
          <div class="p-2.5 mt-2 flex items-center rounded-md px-4 duration-300 cursor-pointer dark:hover:bg-gray-700 hover:bg-gray-400">
            <i class="bi bi-calendar"></i>
            <span class="text-[15px] ml-4 dark:text-gray-200 text-gray-900">Calendar</span>
          </div>
          <div class="p-2.5 mt-2 flex items-center rounded-md px-4 duration-300 cursor-pointer dark:hover:bg-gray-700 hover:bg-gray-400">
            <i class="bi bi-journal"></i>
            <span class="text-[15px] ml-4 dark:text-gray-200 text-gray-900">Semester Planner</span>
          </div>
          <div class="p-2.5 mt-2 flex items-center rounded-md px-4 duration-300 cursor-pointer dark:hover:bg-gray-700 hover:bg-gray-400">
            <i class="bi bi-graph-up-arrow"></i>
            <span class="text-[15px] ml-4 dark:text-gray-200 text-gray-900">Goals</span>
          </div>
          <hr class="my-4 dark:border-gray-600 border-gray-900">
          <div class="p-2.5 mt-2 flex items-center rounded-md px-4 duration-300 cursor-pointer dark:hover:bg-gray-700 hover:bg-gray-400">
            <i class="bi bi-person-fill"></i>
            <span class="text-[15px] ml-4 dark:text-gray-200 text-gray-900">My account</span>
          </div>
          <%= link_to '/logout', method: :get do %>
            <div class="p-2.5 mt-2 flex items-center rounded-md px-4 duration-300 cursor-pointer dark:hover:bg-gray-700 hover:bg-gray-400">
              <i class="bi bi-box-arrow-in-left"></i>
              <span class="text-[15px] ml-4 dark:text-gray-200 text-gray-900">Logout</span>
            </div>
          <% end %>
        <% else %>
          <%= link_to '/login', method: :get do %>
            <div class="p-2.5 mt-2 flex items-center rounded-md px-4 duration-300 cursor-pointer dark:hover:bg-gray-700 hover:bg-gray-400">
              <i class="bi bi-box-arrow-in-right"></i>
              <span class="text-[15px] ml-4 dark:text-gray-200 text-gray-900">Login</span>
            </div>
          <% end %>
          <%= link_to '/users/new', method: :get do %>
            <div class="p-2.5 mt-2 flex items-center rounded-md px-4 duration-300 cursor-pointer dark:hover:bg-gray-700 hover:bg-gray-400">
              <i class="bi bi-person-plus-fill"></i>
              <span class="text-[15px] ml-4 dark:text-gray-200 text-gray-900">Sign up</span>
            </div>
          <% end %>
        <% end %>
        <div data-theme-target="themeToggle" data-action="click->theme#changeTheme" class="p-2.5 mt-2 flex items-center rounded-md px-4 duration-300 cursor-pointer dark:hover:bg-gray-700 hover:bg-gray-400">
            <i id="theme-toggle-dark-icon" class="hidden bi bi-brightness-high-fill"></i>
            <i id="theme-toggle-light-icon" class="hidden bi bi-moon-fill"></i>
            <span class="text-[15px] ml-4 dark:text-gray-200 text-gray-900">Toggle theme</span>
        </div>
      </div>
    </div>
  </div>
  <script>
    const open_nav = () => {
      document.querySelector('.sidebar').classList.toggle('left-[-250px]')
    };
  </script>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="dark">
  <head>
    <title>Planit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body class="dark:bg-gray-800 bg-gray-100 lg:grid text-slate-900 dark:text-slate-200 lg:grid-cols-[250px_50px_auto_50px]">
    <%= render partial: "layouts/navbar" %>
    <div class="invisible"></div>
    <main class="justify-center mt-20 px-5 py-5 flex bg-white shadow-md dark:bg-gray-900 sm:rounded-lg">
      <%= yield %>
    </main>
    <div class="invisible"></div>
  </body>
</html>

app/views/users/new.html.erb
<div>
  <h1 class="font-bold text-3xl text-center pb-5">Create an account</h1>
  <%= form_with model: @user, url: users_path, html: { class: "w-full max-w-sm" } do |f| %>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/3">
        <%= f.label :username, class: "dark:text-gray-100 text-gray-900 block font-bold md:text-right mb-1 md:mb-0 pr-4" %>
      </div>
      <div class="md:w-2/3">
        <%= f.text_field :username, class: "bg-gray-200 text-black appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-900" %>
      </div>
    </div>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/3">
        <%= f.label :password, class: "dark:text-gray-100 text-gray-900 block font-bold md:text-right mb-1 md:mb-0 pr-4" %>
      </div>
      <div class="md:w-2/3">
        <%= f.password_field :password, class: "bg-gray-200 text-black appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-900" %>
      </div>
    </div>
    <div class="md:flex md:items-center mb-6">
      <div class="md:w-1/3">
        <%= f.label :password_confirmation, class: "dark:text-gray-100 text-gray-900 block font-bold md:text-right mb-1 md:mb-0 pr-4" %>
      </div>
      <div class="md:w-2/3">
        <%= f.password_field :password_confirmation, class: "bg-gray-200 text-black appearance-none border-2 border-gray-200 rounded w-full py-2 px-4 leading-tight focus:outline-none focus:bg-white focus:border-gray-900" %>
      </div>
    </div>
    <div class="md:flex md:items-center">
      <div class="md:w-1/3"></div>
      <div class="md:w-2/3">
        <%= f.button "Create account", type: "submit", class: "dark:text-gray-100 text-white shadow bg-blue-800 hover:bg-blue-700 focus:shadow-outline focus:outline-none font-bold py-2 px-4 rounded" %>
      </div>
    </div>
  <% end %>
</div>